query GetFeed($offset: Float, $limit: Float, $source: String, $locale: String) {
  getFeed(offset: $offset, limit: $limit, source: $source, locale: $locale) {
    items {
      id
      title
      summary
      link
      publishedAt
      author
      authorAvatar
      source
    }
    total
    hasMore
  }
}

query GetChangelog($limit: Float, $locale: String) {
  getFeed(offset: 0, limit: $limit, source: "CHANGELOG", locale: $locale) {
    items {
      id
      title
      summary
      link
      publishedAt
      source
    }
    total
    hasMore
  }
}
